#!/bin/sh

#put xinitrc content in this file...

setxkbmap -model acer_laptop -option grp:alt_shift_toggle us,ara
#xset r rate 200 55

sxhkd &

#DWM:-----------------------
systemctl --user start dunst.service
#dunst &

xwallpaper --stretch $XDG_CACHE_HOME/wallpaper
picom -b

#clipmenud &
systemctl --user start clipmenud.service

dwmblocks &

exec dwm
#---------------------------
